apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-realworld-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-express-realworld
  template:
    metadata:
      labels:
        app: node-express-realworld
    spec:
      containers:
      - name: node-express-app
        image: wafaselmi/kubernetes-node
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /api/
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
