apiVersion: v1
kind: Service
metadata:
  name: node-express-realworld-service
spec:
  selector:
    app: node-express-realworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-express-realworld-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-express-realworld-service
            port:
              number: 80